// 格式：{ id: 唯一編號, chinese: "中文", english: "英文", pos: "詞性" }
// 詞性代碼：n.名詞 v.動詞 adj.形容詞 adv.副詞 prep.介系詞 conj.連接詞 pron.代名詞
const WORDS = [
  { id: 1, chinese: "使凝固", english: "solidify", pos: "v." },
  { id: 2, chinese: "離心的", english: "centrifugal", pos: "adj." },
  { id: 3, chinese: "隔絕", english: "insulate", pos: "v." },
  { id: 4, chinese: "不透明的", english: "opaque", pos: "adj." },
  { id: 5, chinese: "有浮力的", english: "buoyant", pos: "adj." },
  { id: 6, chinese: "翻覆", english: "capsize", pos: "v." },
  { id: 7, chinese: "照明、闡明", english: "illuminate", pos: "v." },
  { id: 8, chinese: "變形、扣住", english: "buckle", pos: "v." },
  { id: 9, chinese: "熔爐", english: "furnace", pos: "n." },
  { id: 10, chinese: "時間的、世俗的", english: "temporal", pos: "adj." },
  { id: 11, chinese: "有彈性的", english: "elastic", pos: "adj." },
  { id: 12, chinese: "恢復", english: "revert", pos: "v." },
  { id: 13, chinese: "利用", english: "harness", pos: "v." },
  { id: 14, chinese: "凹面的", english: "concave", pos: "adj." },
  { id: 15, chinese: "柔軟的", english: "pliable", pos: "adj." },
  { id: 16, chinese: "速度", english: "velocity", pos: "n." },
  { id: 17, chinese: "旋轉", english: "whirl", pos: "v." },
  { id: 18, chinese: "密封的", english: "airtight", pos: "adj." },
  { id: 19, chinese: "可塑的、易受影響的", english: "malleable", pos: "adj." },
  { id: 20, chinese: "電路", english: "circuit", pos: "n." },
  { id: 21, chinese: "慣性、惰性", english: "inertia", pos: "n." },
  { id: 22, chinese: "對流", english: "convection", pos: "n." },
  { id: 23, chinese: "鹽的", english: "saline", pos: "adj." },
  { id: 24, chinese: "漏斗、煙囪", english: "funnel", pos: "n." },
  { id: 25, chinese: "易燃的", english: "inflammable", pos: "adj." },
  { id: 26, chinese: "防腐劑", english: "preservative", pos: "n." },
  { id: 27, chinese: "生鏽、鏽", english: "rust", pos: "v./ n." },
  { id: 28, chinese: "起泡沫、泡沫", english: "froth", pos: "v./ n." },
  { id: 29, chinese: "粘稠的", english: "viscous", pos: "adj." },
  { id: 30, chinese: "石膏、ok繃", english: "plaster", pos: "n." },
  { id: 31, chinese: "成分", english: "constituent", pos: "n." },
  { id: 32, chinese: "白熾的", english: "incandescent", pos: "adj." },
  { id: 33, chinese: "粗糙的", english: "coarse", pos: "adj." },
  { id: 34, chinese: "惰性的、沒有活力的", english: "inert", pos: "adj." },
  { id: 35, chinese: "崩解、瓦解", english: "disintegrate", pos: "v." },
  { id: 36, chinese: "冒煙、悶燒", english: "smoulder", pos: "v." },
  { id: 37, chinese: "合金", english: "alloy", pos: "n." },
  { id: 38, chinese: "硫磺", english: "sulphur", pos: "n." },
  { id: 39, chinese: "鈾", english: "uranium", pos: "n." },
  { id: 40, chinese: "黃銅", english: "brass", pos: "n." },
  { id: 41, chinese: "圓錐形的", english: "conical", pos: "adj." },
  { id: 42, chinese: "幾何的", english: "geometric", pos: "adj." },
  { id: 43, chinese: "減法", english: "subtraction", pos: "n." },
  { id: 44, chinese: "乘法", english: "multiplication", pos: "n." },
  { id: 45, chinese: "方程式", english: "equation", pos: "n." },
  { id: 46, chinese: "三角函數", english: "trigonometry", pos: "n." },
  { id: 47, chinese: "拋物線", english: "parabola", pos: "n." },
  { id: 48, chinese: "對角線", english: "diagonal", pos: "n." },
  { id: 49, chinese: "圓周", english: "circumference", pos: "n." },
  { id: 50, chinese: "角柱體", english: "prism", pos: "n." },
  { id: 51, chinese: "有粘性的、黏著劑", english: "adhesive", pos: "adj./ n." },
  { id: 52, chinese: "模具、影響改變", english: "mould", pos: "n./ v." },
  { id: 53, chinese: "刻度、等級", english: "caliber", pos: "n." },
  { id: 54, chinese: "支撐、增強", english: "bolster", pos: "v." },
  { id: 55, chinese: "刺破、小孔", english: "puncture", pos: "v./ n." },
  { id: 56, chinese: "自動操作的、自主的", english: "autonomous", pos: "adj." },
  { id: 57, chinese: "合成的、人造的", english: "synthetic", pos: "adj." },
  { id: 58, chinese: "楔形物", english: "wedge", pos: "n." },
  { id: 59, chinese: "壓碎、壓扁", english: "squash", pos: "v." },
  { id: 60, chinese: "礦石", english: "ore", pos: "n." },
  { id: 61, chinese: "閃避（問題）、使轉向", english: "deflect", pos: "v." },
  { id: 62, chinese: "一縷、一陣、吹出", english: "puff", pos: "n./ v." },
  { id: 63, chinese: "使堅固、使強化", english: "toughen", pos: "v." },
  { id: 64, chinese: "下垂、凹陷", english: "sag", pos: "v." },
  { id: 65, chinese: "週期的", english: "periodic", pos: "adj." },
  { id: 66, chinese: "堅固的、穩健的", english: "sturdy", pos: "adj." },
  { id: 67, chinese: "原型", english: "prototype", pos: "n." },
  { id: 68, chinese: "網格、電網", english: "grid", pos: "n." },
  { id: 69, chinese: "可想像的、可相信的", english: "conceivable", pos: "adj." },
  { id: 70, chinese: "（負面）影響、侵犯（權利）", english: "impinge", pos: "v." },
  { id: 71, chinese: "無處不在的", english: "ubiquitous", pos: "adj." },
  { id: 72, chinese: "無處不在、隨處可見", english: "ubiquity", pos: "n." },
  { id: 73, chinese: "微調、小幅度修改", english: "tweak", pos: "v." },
  { id: 74, chinese: "小裝置、小工具", english: "gizmo", pos: "n." },
  { id: 75, chinese: "煉金術", english: "alchemy", pos: "n." },
  { id: 76, chinese: "可預見的", english: "foreseeable", pos: "adj." },
  { id: 77, chinese: "鐘擺", english: "pendulum", pos: "n." },
  { id: 78, chinese: "淺在的困難危險、陷阱", english: "pitfall", pos: "n." },
  { id: 79, chinese: "小錯誤、小瑕疵", english: "glitch", pos: "n." },
  { id: 80, chinese: "指數增長的、快速增加的", english: "exponential", pos: "adj." },
  { id: 81, chinese: "過時的", english: "outdated", pos: "adj." },
  { id: 82, chinese: "授予、給予", english: "bestow", pos: "v." },
  { id: 83, chinese: "化身、具現", english: "incarnation", pos: "n." },
  { id: 84, chinese: "精確度、忠誠、忠實", english: "fidelity", pos: "n." },
  { id: 85, chinese: "包含、納入", english: "incorporate", pos: "v." },
  { id: 86, chinese: "標準規範、規格書", english: "specification", pos: "n." },
  { id: 87, chinese: "古老的、過時的", english: "antiquated", pos: "adj." },
  { id: 88, chinese: "令人困惑的、難以理解的", english: "bewildering", pos: "adj." },
  { id: 89, chinese: "漫遊、徘徊", english: "roam", pos: "v." },
  { id: 90, chinese: "編碼", english: "encode", pos: "v." },
  { id: 91, chinese: "努力、嘗試", english: "endeavour", pos: "n." },
  { id: 92, chinese: "過時的", english: "outmoded", pos: "adj." },
  { id: 93, chinese: "稍微染色、色調", english: "tint", pos: "v./ n." },
  { id: 94, chinese: "恩惠、好處", english: "boon", pos: "n." },
  { id: 95, chinese: "引導、帶領", english: "usher", pos: "v." },
  { id: 96, chinese: "取代、替代", english: "supplant", pos: "v." },
  { id: 97, chinese: "立體的", english: "stereoscopic", pos: "adj." },
  { id: 98, chinese: "小工具", english: "gadget", pos: "n." },
  { id: 99, chinese: "配置", english: "configuration", pos: "n." },
  { id: 100, chinese: "突飛猛進的、量子", english: "quantum", pos: "adj./ n." },
  { id: 101, chinese: "水泥", english: "cement", pos: "n." },
  { id: 102, chinese: "螺絲起子", english: "screwdriver", pos: "n." },
  { id: 103, chinese: "螺栓", english: "bolt", pos: "n." },
  { id: 104, chinese: "木炭", english: "charcoal", pos: "n." },
  { id: 105, chinese: "無固定形狀的", english: "amorphous", pos: "adj." },
  { id: 106, chinese: "空虛的、虛無、空虛感", english: "void", pos: "adj./ n." },
  { id: 107, chinese: "宇宙的", english: "cosmic", pos: "adj." },
  { id: 108, chinese: "放大", english: "magnify", pos: "v." },
  { id: 109, chinese: "天空的、太空的", english: "celestial", pos: "adj." },
  { id: 110, chinese: "推進、推動", english: "propel", pos: "v." },
  { id: 111, chinese: "旋轉", english: "revolve", pos: "v." },
  { id: 112, chinese: "方向感、態度、影響", english: "bearing", pos: "n." },
  { id: 113, chinese: "外星人", english: "extraterrestrial", pos: "n." },
  { id: 114, chinese: "星雲", english: "nebula", pos: "n." },
  { id: 115, chinese: "小行星", english: "asteroid", pos: "n." },
  { id: 116, chinese: "星座", english: "constellation", pos: "n." },
  { id: 117, chinese: "流星", english: "meteor", pos: "n." },
  { id: 118, chinese: "隕石", english: "meteorite", pos: "n." },
  { id: 119, chinese: "無人操縱的", english: "unmanned", pos: "adj." },
  { id: 120, chinese: "暴雨般的、急流般的", english: "torrential", pos: "adj." },
  { id: 121, chinese: "解凍", english: "thaw", pos: "v./ n." },
  { id: 122, chinese: "悶熱的、令人窒息的", english: "stuffy", pos: "adj." },
  { id: 123, chinese: "冰雹、招呼呼叫", english: "hail", pos: "n./ v." },
  { id: 124, chinese: "降水（量）", english: "precipitation", pos: "n." },
  { id: 125, chinese: "暴雨、大雨", english: "downpour", pos: "n." },
  { id: 126, chinese: "溫和的、適中的、有節制的", english: "temperate", pos: "adj." },
  { id: 127, chinese: "悶熱的、潮濕的", english: "muggy", pos: "adj." },
  { id: 128, chinese: "細雨、灑水", english: "sprinkle", pos: "v./ n." },
  { id: 129, chinese: "暴風雪", english: "blizzard", pos: "n." },
  { id: 130, chinese: "霜", english: "frost", pos: "n." },
  { id: 131, chinese: "薄霧", english: "haze", pos: "n." },
  { id: 132, chinese: "大風", english: "gale", pos: "n." },
  { id: 133, chinese: "陣風", english: "gust", pos: "n." },
  { id: 134, chinese: "季風", english: "monsoon", pos: "n." },
  { id: 135, chinese: "濕度計", english: "hygrometer", pos: "n." },
  { id: 136, chinese: "氣壓計", english: "barometer", pos: "n." },
  { id: 137, chinese: "滲透", english: "permeate", pos: "v." },
  { id: 138, chinese: "河口", english: "estuary", pos: "n." },
  { id: 139, chinese: "高原、停滯期", english: "plateau", pos: "n." },
  { id: 140, chinese: "熔化的", english: "molten", pos: "adj." },
  { id: 141, chinese: "群島", english: "archipelago", pos: "n." },
  { id: 142, chinese: "地形", english: "terrain", pos: "n." },
  { id: 143, chinese: "地殼、吐司邊", english: "crust", pos: "n." },
  { id: 144, chinese: "沼澤、濕地", english: "marsh", pos: "n." },
  { id: 145, chinese: "輕微顫抖的", english: "tremulous", pos: "adj." },
  { id: 146, chinese: "玄武岩", english: "basalt", pos: "n." },
  { id: 147, chinese: "地函", english: "mantle", pos: "n." },
  { id: 148, chinese: "貫穿、滲透", english: "penetrate", pos: "v." },
  { id: 149, chinese: "凹槽、習慣", english: "groove", pos: "n." },
  { id: 150, chinese: "含水層", english: "aquifer", pos: "n." },
  { id: 151, chinese: "休眠的、靜止的", english: "dormant", pos: "adj." },
  { id: 152, chinese: "裂開、目瞪口呆的看", english: "gape", pos: "v." },
  { id: 153, chinese: "雪崩、蜂擁而至", english: "avalanche", pos: "n." },
  { id: 154, chinese: "淤泥", english: "silt", pos: "n." },
  { id: 155, chinese: "內陸、偏遠地區", english: "hinterland", pos: "n." },
  { id: 156, chinese: "荒涼的", english: "desolate", pos: "adj." },
  { id: 157, chinese: "內陸的", english: "inland", pos: "adj." },
  { id: 158, chinese: "地形（圖）", english: "topography", pos: "n." },
  { id: 159, chinese: "溝渠", english: "trench", pos: "n." },
  { id: 160, chinese: "沼澤、使無法負荷", english: "swamp", pos: "n./ v." },
  { id: 161, chinese: "侵蝕", english: "erode", pos: "v." },
  { id: 162, chinese: "南極洲", english: "Antarctica", pos: "n." },
  { id: 163, chinese: "大陸", english: "continent", pos: "n." },
  { id: 164, chinese: "赤道", english: "equator", pos: "n." },
  { id: 165, chinese: "峽谷", english: "canyon", pos: "n." },
  { id: 166, chinese: "盆地", english: "basin", pos: "n." },
  { id: 167, chinese: "潮汐", english: "tide", pos: "n." },
  { id: 168, chinese: "海角", english: "cape", pos: "n." },
  { id: 169, chinese: "大理石", english: "marble", pos: "n." },
  { id: 170, chinese: "地震儀", english: "seismograph", pos: "n." },
  { id: 171, chinese: "伐木", english: "logging", pos: "n." },
  { id: 172, chinese: "驟降、倒塌、摔倒", english: "tumble", pos: "v./ n." },
  { id: 173, chinese: "即將到來的、迫近的", english: "imminent", pos: "adj." },
  { id: 174, chinese: "滲漏、滲出", english: "seep", pos: "v." },
  { id: 175, chinese: "削減、縮減", english: "curtail", pos: "v." },
  { id: 176, chinese: "污泥、淤泥", english: "sludge", pos: "n." },
  { id: 177, chinese: "惡劣的、有敵意的", english: "hostile", pos: "adj." },
  { id: 178, chinese: "缺乏、不足", english: "scarcity", pos: "n." },
  { id: 179, chinese: "威脅、恐嚇", english: "menace", pos: "n./ v." },
  { id: 180, chinese: "垃圾填埋場", english: "landfill", pos: "n." },
  { id: 181, chinese: "逐漸逼近、顯現", english: "loom", pos: "v./ n." },
  { id: 182, chinese: "毀滅、大量殺傷", english: "decimate", pos: "v." },
  { id: 183, chinese: "易燃的", english: "combustible", pos: "adj." },
  { id: 184, chinese: "必要的、緊急的", english: "imperative", pos: "adj." },
  { id: 185, chinese: "罪犯、 肇因", english: "culprit", pos: "n." },
  { id: 186, chinese: "殘留物", english: "residue", pos: "n." },
  { id: 187, chinese: "聖地、禁獵區", english: "sanctuary", pos: "n." },
  { id: 188, chinese: "實用主義的、務實的", english: "pragmatic", pos: "adj." },
  { id: 189, chinese: "造成、引發", english: "wreak", pos: "v." },
  { id: 190, chinese: "補償、抵消", english: "offset", pos: "v./ n." },
  { id: 191, chinese: "主要影響、衝擊", english: "brunt", pos: "n." },
  { id: 192, chinese: "混亂、破壞", english: "havoc", pos: "n." },
  { id: 193, chinese: "積極主動的", english: "proactive", pos: "adj." },
  { id: 194, chinese: "任意的、無差別的", english: "indiscriminate", pos: "adj." },
  { id: 195, chinese: "不可逆轉的", english: "irrevocable", pos: "adj." },
  { id: 196, chinese: "焚化", english: "incineration", pos: "n." },
  { id: 197, chinese: "處置、處理", english: "disposal", pos: "n." },
  { id: 198, chinese: "完全消滅、毀滅", english: "annihilate", pos: "v." },
  { id: 199, chinese: "石油", english: "petroleum", pos: "n." },
  { id: 200, chinese: "喘氣", english: "pant", pos: "v./ n." },
  { id: 201, chinese: "易受影響的", english: "susceptible", pos: "adj." },
  { id: 202, chinese: "陸地的", english: "terrestrial", pos: "adj." },
  { id: 203, chinese: "上岸、向岸上", english: "ashore", pos: "adv." },
  { id: 204, chinese: "（發出）吱吱聲", english: "squeak", pos: "v./ n." },
  { id: 205, chinese: "有害的", english: "noxious", pos: "adj." },
  { id: 206, chinese: "（昆蟲）變態、使變形", english: "metamorphose", pos: "v." },
  { id: 207, chinese: "裂縫、切口", english: "slit", pos: "n." },
  { id: 208, chinese: "滲出、慢慢流動", english: "ooze", pos: "v." },
  { id: 209, chinese: "附肢、附屬物", english: "appendage", pos: "n." },
  { id: 210, chinese: "營養、養分", english: "nourishment", pos: "n." },
  { id: 211, chinese: "避開、回避", english: "shun", pos: "v." },
  { id: 212, chinese: "滑行、滑溜", english: "slither", pos: "v." },
  { id: 213, chinese: "優勢、有利位置、視角", english: "vantage", pos: "n." },
  { id: 214, chinese: "輕咬、捏", english: "nip", pos: "v./ n." },
  { id: 215, chinese: "扭打", english: "scuffle", pos: "n." },
  { id: 216, chinese: "污染", english: "contamination", pos: "n." },
  { id: 217, chinese: "生物群落", english: "biotope", pos: "n." },
  { id: 218, chinese: "有袋動物", english: "marsupial", pos: "n." },
  { id: 219, chinese: "犬科動物", english: "canine", pos: "n." },
  { id: 220, chinese: "鬃毛", english: "mane", pos: "n." },
  { id: 221, chinese: "蹄", english: "hoof", pos: "n." },
  { id: 222, chinese: "蛹", english: "pupa", pos: "n." },
  { id: 223, chinese: "繭", english: "cocoon", pos: "n." },
  { id: 224, chinese: "鰓", english: "gill", pos: "n." },
  { id: 225, chinese: "鱗片", english: "scale", pos: "n." },
  { id: 226, chinese: "冬眠", english: "hibernation", pos: "n." },
  { id: 227, chinese: "俘虜、被囚禁的", english: "captive", pos: "n./ adj." },
  { id: 228, chinese: "異國的、外來的", english: "exotic", pos: "adj." },
  { id: 229, chinese: "優越性", english: "superiority", pos: "n." },
  { id: 230, chinese: "笨重的、龐大的", english: "bulky", pos: "adj." },
  { id: 231, chinese: "有毒的", english: "venomous", pos: "adj." },
  { id: 232, chinese: "挖掘洞穴、洞穴", english: "burrow", pos: "v./ n." },
  { id: 233, chinese: "著陸、降落在…上", english: "alight", pos: "v." },
  { id: 234, chinese: "緊緊抓住、依附", english: "cling", pos: "v." },
  { id: 235, chinese: "誘餌", english: "decoy", pos: "n." },
  { id: 236, chinese: "突出、伸出", english: "protrude", pos: "v." },
  { id: 237, chinese: "解剖學", english: "anatomy", pos: "n." },
  { id: 238, chinese: "纏住", english: "entangle", pos: "v." },
  { id: 239, chinese: "承受、忍受", english: "withstand", pos: "v." },
  { id: 240, chinese: "求愛、求偶", english: "courtship", pos: "n." },
  { id: 241, chinese: "夜間的、夜行性的", english: "nocturnal", pos: "adj." },
  { id: 242, chinese: "機動、操作", english: "manoeuvre", pos: "n./ v." },
  { id: 243, chinese: "條紋、斑紋", english: "streak", pos: "n." },
  { id: 244, chinese: "藏匿、隱藏", english: "stash", pos: "v." },
  { id: 245, chinese: "產卵、孵化", english: "spawn", pos: "v." },
  { id: 246, chinese: "棲息、棲息處", english: "perch", pos: "v./ n." },
  { id: 247, chinese: "氣味、香氣", english: "odour", pos: "n." },
  { id: 248, chinese: "髒的、污穢的", english: "filthy", pos: "adj." },
  { id: 249, chinese: "坚持不懈", english: "perseverance", pos: "n." },
  { id: 250, chinese: "大量存在、繁盛", english: "abound", pos: "v." },
  { id: 251, chinese: "補充、補給", english: "replenish", pos: "v." },
  { id: 252, chinese: "誘餌", english: "bait", pos: "n." },
  { id: 253, chinese: "地方性的、土生土長的", english: "endemic", pos: "adj." },
  { id: 254, chinese: "難以捉摸的、難以理解的", english: "elusive", pos: "adj." },
  { id: 255, chinese: "雛鳥", english: "brood", pos: "n." },
  { id: 256, chinese: "轉動、旋轉", english: "swivel", pos: "v." },
  { id: 257, chinese: "橫穿、穿越", english: "traverse", pos: "v." },
  { id: 258, chinese: "鶴", english: "crane", pos: "n." },
  { id: 259, chinese: "白蟻", english: "termite", pos: "n." },
  { id: 260, chinese: "蜈蚣", english: "centipede", pos: "n." },
  { id: 261, chinese: "小枝、細枝", english: "twigs", pos: "n." },
  { id: 262, chinese: "灌木", english: "shrub", pos: "n." },
  { id: 263, chinese: "多刺的、帶刺的", english: "thorny", pos: "adj." },
  { id: 264, chinese: "花蜜", english: "tectar", pos: "n." },
  { id: 265, chinese: "授粉", english: "pollinate", pos: "v." },
  { id: 266, chinese: "樹冠", english: "canopy", pos: "n." },
  { id: 267, chinese: "茂盛的、繁茂的", english: "lush", pos: "adj." },
  { id: 268, chinese: "樹林", english: "grove", pos: "n." },
  { id: 269, chinese: "繁殖、傳播", english: "propagate", pos: "v.  " },
  { id: 270, chinese: "發芽", english: "germinate", pos: "v." },
  { id: 271, chinese: "散播、分散", english: "disperse", pos: "v." },
  { id: 272, chinese: "花瓣", english: "petal", pos: "n." },
  { id: 273, chinese: "放棄、拒絕", english: "forgo", pos: "v." },
  { id: 274, chinese: "清除、剷除", english: "eradicate", pos: "v." },
  { id: 275, chinese: "探索性的", english: "exploratory", pos: "adj." },
  { id: 276, chinese: "使絕育、消毒殺菌", english: "sterilise", pos: "v." },
  { id: 277, chinese: "擦洗、刷洗", english: "scrub", pos: "v." },
  { id: 278, chinese: "弱小的、無力的", english: "feeble", pos: "adj." },
  { id: 279, chinese: "赤字、缺陷", english: "deficit", pos: "n." },
  { id: 280, chinese: "疾病、不適", english: "ailment", pos: "n." },
  { id: 281, chinese: "空氣傳播的", english: "airborne", pos: "adj." },
  { id: 282, chinese: "使康復", english: "rehabilitate", pos: "v." },
  { id: 283, chinese: "侷限", english: "localise", pos: "v." },
  { id: 284, chinese: "使苦惱、經常出沒", english: "haunt", pos: "v." },
  { id: 285, chinese: "過早的", english: "premature", pos: "adj." },
  { id: 286, chinese: "令人苦惱的、悲慘的", english: "distressing", pos: "adj." },



];
