// 單字資料庫 - 直接在這裡新增或編輯單字
// 格式：{ id: 唯一編號, chinese: "中文", english: "英文", pos: "詞性" }
// 詞性代碼：n.名詞 v.動詞 adj.形容詞 adv.副詞 prep.介系詞 conj.連接詞 pron.代名詞
const WORDS = [
  { id: 1, chinese: "使凝固", english: "solidify", pos: "v." },
  { id: 2, chinese: "離心的", english: "centrifugal", pos: "adj." },
  { id: 3, chinese: "隔絕", english: "insulate", pos: "v." },
  { id: 4, chinese: "不透明的", english: "opaque", pos: "adj." },
  { id: 5, chinese: "有浮力的", english: "buoyant", pos: "adj." },
  { id: 6, chinese: "翻覆", english: "capsize", pos: "v." },
  { id: 7, chinese: "照明、闡明", english: "illuminate", pos: "v." },
  { id: 8, chinese: "變形、扣住", english: "buckle", pos: "v." },
  { id: 9, chinese: "熔爐", english: "furnace", pos: "n." },
  { id: 10, chinese: "時間的、世俗的", english: "temporal", pos: "adj." },
  { id: 11, chinese: "有彈性的", english: "elastic", pos: "adj." },
  { id: 12, chinese: "恢復", english: "revert", pos: "v." },
  { id: 13, chinese: "利用", english: "harness", pos: "v." },
  { id: 14, chinese: "凹面的", english: "concave", pos: "adj." },
  { id: 15, chinese: "柔軟的", english: "pliable", pos: "adj." },
  { id: 16, chinese: "速度", english: "velocity", pos: "n." },
  { id: 17, chinese: "旋轉", english: "whirl", pos: "v." },
  { id: 18, chinese: "密封的", english: "airtight", pos: "adj." },
  { id: 19, chinese: "可塑的、易受影響的", english: "malleable", pos: "adj." },
  { id: 20, chinese: "電路", english: "circuit", pos: "n." },
  { id: 21, chinese: "慣性、惰性", english: "inertia", pos: "n." },
  { id: 22, chinese: "對流", english: "convection", pos: "n." },
  { id: 23, chinese: "鹽的", english: "saline", pos: "adj." },
  { id: 24, chinese: "漏斗、煙囪", english: "funnel", pos: "n." },
  { id: 25, chinese: "易燃的", english: "inflammable", pos: "adj." },
  { id: 26, chinese: "防腐劑", english: "preservative", pos: "n." },
  { id: 27, chinese: "生鏽、鏽", english: "rust", pos: "v./ n." },
  { id: 28, chinese: "起泡沫、泡沫", english: "froth", pos: "v./ n." },
  { id: 29, chinese: "粘稠的", english: "viscous", pos: "adj." },
  { id: 30, chinese: "石膏、ok繃", english: "plaster", pos: "n." },
  { id: 31, chinese: "成分", english: "constituent", pos: "n." },
  { id: 32, chinese: "白熾的", english: "incandescent", pos: "adj." },
  { id: 33, chinese: "粗糙的", english: "coarse", pos: "adj." },
  { id: 34, chinese: "惰性的、沒有活力的", english: "inert", pos: "adj." },
  { id: 35, chinese: "崩解、瓦解", english: "disintegrate", pos: "v." },
  { id: 36, chinese: "冒煙、悶燒", english: "smoulder", pos: "v." },
  { id: 37, chinese: "合金", english: "alloy", pos: "n." },
  { id: 38, chinese: "硫磺", english: "sulphur", pos: "n." },
  { id: 39, chinese: "鈾", english: "uranium", pos: "n." },
  { id: 40, chinese: "黃銅", english: "brass", pos: "n." },
  { id: 41, chinese: "圓錐形的", english: "conical", pos: "adj." },
  { id: 42, chinese: "幾何的", english: "geometric", pos: "adj." },
  { id: 43, chinese: "減法", english: "subtraction", pos: "n." },
  { id: 44, chinese: "乘法", english: "multiplication", pos: "n." },
  { id: 45, chinese: "方程式", english: "equation", pos: "n." },
  { id: 46, chinese: "三角函數", english: "trigonometry", pos: "n." },
  { id: 47, chinese: "拋物線", english: "parabola", pos: "n." },
  { id: 48, chinese: "對角線", english: "diagonal", pos: "n." },
  { id: 49, chinese: "圓周", english: "circumference", pos: "n." },
  { id: 50, chinese: "角柱體", english: "prism", pos: "n." },
  { id: 51, chinese: "有粘性的、黏著劑", english: "adhesive", pos: "adj./ n." },
  { id: 52, chinese: "模具、影響改變", english: "mould", pos: "n./ v." },
  { id: 53, chinese: "刻度、等級", english: "caliber", pos: "n." },
  { id: 54, chinese: "支撐、增強", english: "bolster", pos: "v." },
  { id: 55, chinese: "刺破、小孔", english: "puncture", pos: "v./ n." },
  { id: 56, chinese: "自動操作的、自主的", english: "autonomous", pos: "adj." },
  { id: 57, chinese: "合成的、人造的", english: "synthetic", pos: "adj." },
  { id: 58, chinese: "楔形物", english: "wedge", pos: "n." },
  

];
